# Generated by Django 6.0.3 on 2026-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt'),
        ),
    ]
